services:
  - type: web
    name: POCKET_SIGNAL_BOT
    runtime: python
    plan: free
    branch: main

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium firefox chrome

    startCommand: python main.py

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.11

      - key: BOT_TOKEN
        sync: false

      - key: OWNER_ID
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: PO_EMAIL
        sync: false

      - key: PO_PASSWORD
        sync: false

      - key: PO_SSID
        sync: false

      - key: PO_AUTO_LOGIN
        value: "true"

      - key: PO_DEMO
        value: "true"

      - key: JOIN_REQUIRED
        value: "false"

      - key: MIN_SIGNAL_SCORE
        value: "75"

      - key: MIN_PROBABILITY
        value: "75"

      - key: SCAN_INTERVAL
        value: "60"

      - key: TIMEZONE
        value: "Europe/Moscow"
