services:
  - type: web
    name: pocket-signal-bot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt && playwright install chromium

    startCommand: python main.py

    envVars:

      - key: BOT_TOKEN
        sync: false

      - key: OWNER_ID
        sync: false

      - key: DATABASE_URL
        fromDatabase:
          name: pocket-signal-db
          property: connectionString

      - key: JOIN_REQUIRED
        value: "false"

      - key: MIN_SIGNAL_SCORE
        value: "75"

      - key: MIN_PROBABILITY
        value: "75"

      - key: SCAN_INTERVAL
        value: "30"

      - key: TIMEZONE
        value: "Europe/Moscow"

      - key: PO_EMAIL
        sync: false

      - key: PO_PASSWORD
        sync: false

      - key: PO_AUTO_LOGIN
        value: "true"

      - key: PO_DEMO
        value: "true"


databases:

  - name: pocket-signal-db
    plan: free
